project_id = "mvndgpmetndvjsmvhqqh"

[functions.handle-inbound-whatsapp]
verify_jwt = false

[functions.handle-inbound-email] 
verify_jwt = false

[functions.ai-ask]
verify_jwt = false

[functions.ai-draft]
verify_jwt = false

[functions.enrich-customer]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.ai-sdk]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-text]
verify_jwt = false

[functions.research-customer]
verify_jwt = false

[functions.csv-import]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = false

[functions.marketing-generate-image]
verify_jwt = true

[functions.ask-fred]
verify_jwt = false

[functions.get-dashboard-metrics]
verify_jwt = false

[functions.validate-csv-format]
verify_jwt = false

[functions.import-arketa-csv]
verify_jwt = false

[functions.create-daily-snapshot]
verify_jwt = false

[functions.calculate-customer-segment]
verify_jwt = false

[functions.detect-segment-changes]
verify_jwt = false

[functions.get-intro-duration]
verify_jwt = false

[functions.process-sequence-automation]
verify_jwt = false

[functions.start-customer-journey]
verify_jwt = false

[functions.send-twilio-whatsapp]
verify_jwt = false
