project_id = "mvndgpmetndvjsmvhqqh"

[functions.ai-ask]
verify_jwt = false

[functions.ai-draft]
verify_jwt = false

[functions.enrich-customer]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.ai-sdk]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-text]
verify_jwt = false

[functions.research-customer]
verify_jwt = false

[functions.csv-import]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = false

[functions.marketing-generate-image]
verify_jwt = true

[functions.ask-fred]
verify_jwt = false

[functions.get-dashboard-metrics]
verify_jwt = false
